# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more!!!!!!:
# https://aka.ms/yaml

trigger:
- none

parameters:
- name: experimentalTemplate
  displayName: 'Use experimental build process?'
  type: boolean
  default: false

stages:
- stage: invoke_the_code
  jobs:
  - job: invoke_the_code
    workspace:
      clean: all
    steps:
    - ${{ if eq(parameters.experimentalTemplate, true) }}:
           - template: ./template/dotnet.yml
    - ${{ if not(eq(parameters.experimentalTemplate, true)) }}:
           - template: ./template/terraform.yml