trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /First_Folder/*

pool:
  vmImage: ubuntu-latest

# Don't run against PRs
pr: none

stages :
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: "Install"
        inputs:
           terraformVersion: 0.13.4
      - task: TerraformTaskV1@0
        displayName: 'init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'ARM'
          backendAzureRmResourceGroupName: 'ADO'
          backendAzureRmStorageAccountName: 'adostg'
          backendAzureRmContainerName: 'adocontain'
          backendAzureRmKey: 'first'
  - stage: plan
    dependsOn: [validate]
    condition: succeeded('validate')
    jobs:
     - job: terraform_plan_develop
       steps:
         - checkout: self
         - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
           displayName: "Install Terraform 0.13.4"
           inputs:
              terraformVersion: 0.13.4
         - task: TerraformTaskV1@0
           displayName: 'init'
           inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'ARM'
            backendAzureRmResourceGroupName: 'ADO'
            backendAzureRmStorageAccountName: 'adostg'
            backendAzureRmContainerName: 'adocontain'
            backendAzureRmKey: 'second'
         - task: TerraformTaskV1@0
           inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'ARM'
  - stage: apply
    dependsOn: [plan]
    condition: succeeded('plan')
    jobs:
    - job: terraform_apply_develop
      steps: 
      - checkout:  self
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: "Install Terraform 0.13.4"
        inputs:
            terraformVersion: 0.13.4
      - task: TerraformTaskV1@0
        displayName: 'init'
        inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'ARM'
            backendAzureRmResourceGroupName: 'ADO'
            backendAzureRmStorageAccountName: 'adostg'
            backendAzureRmContainerName: 'adocontain'
            backendAzureRmKey: 'first'
      - task: TerraformTaskV1@0
        inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'ARM'
      - task: TerraformTaskV2@2
        inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'ARM'